name: Merge Schedule
on:
  pull_request:
    types:
      - closed
  schedule:
    # https://crontab.guru/every-hour
    - cron: 0 * * * *

jobs:
  merge_branches:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
      - uses: actions/checkout@main

      - name: Merge develop -> main
        uses: devmasx/merge-branch@v1.3.1
        with:
          type: now
          from_branch: develop
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
